// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: server/proto/pbauth/auth.proto

package pbauth

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signup int32

const (
	Signup_ActionSignupAccount Signup = 0
	Signup_ActionSignupCode    Signup = 1
	Signup_ActionSignupConfirm Signup = 2
)

// Enum value maps for Signup.
var (
	Signup_name = map[int32]string{
		0: "ActionSignupAccount",
		1: "ActionSignupCode",
		2: "ActionSignupConfirm",
	}
	Signup_value = map[string]int32{
		"ActionSignupAccount": 0,
		"ActionSignupCode":    1,
		"ActionSignupConfirm": 2,
	}
)

func (x Signup) Enum() *Signup {
	p := new(Signup)
	*p = x
	return p
}

func (x Signup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signup) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_pbauth_auth_proto_enumTypes[0].Descriptor()
}

func (Signup) Type() protoreflect.EnumType {
	return &file_server_proto_pbauth_auth_proto_enumTypes[0]
}

func (x Signup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signup.Descriptor instead.
func (Signup) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_pbauth_auth_proto_rawDescGZIP(), []int{0}
}

type Signin int32

const (
	Signin_ActionSigninAccount Signin = 0
	Signin_ActionSigninCode    Signin = 1
	Signin_ActionSigninConfirm Signin = 2
)

// Enum value maps for Signin.
var (
	Signin_name = map[int32]string{
		0: "ActionSigninAccount",
		1: "ActionSigninCode",
		2: "ActionSigninConfirm",
	}
	Signin_value = map[string]int32{
		"ActionSigninAccount": 0,
		"ActionSigninCode":    1,
		"ActionSigninConfirm": 2,
	}
)

func (x Signin) Enum() *Signin {
	p := new(Signin)
	*p = x
	return p
}

func (x Signin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signin) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_pbauth_auth_proto_enumTypes[1].Descriptor()
}

func (Signin) Type() protoreflect.EnumType {
	return &file_server_proto_pbauth_auth_proto_enumTypes[1]
}

func (x Signin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signin.Descriptor instead.
func (Signin) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_pbauth_auth_proto_rawDescGZIP(), []int{1}
}

type Reset int32

const (
	Reset_ActionResetAccount  Reset = 0
	Reset_ActionResetCode     Reset = 1
	Reset_ActionResetConfirm  Reset = 2
	Reset_ActionResetPassword Reset = 3
)

// Enum value maps for Reset.
var (
	Reset_name = map[int32]string{
		0: "ActionResetAccount",
		1: "ActionResetCode",
		2: "ActionResetConfirm",
		3: "ActionResetPassword",
	}
	Reset_value = map[string]int32{
		"ActionResetAccount":  0,
		"ActionResetCode":     1,
		"ActionResetConfirm":  2,
		"ActionResetPassword": 3,
	}
)

func (x Reset) Enum() *Reset {
	p := new(Reset)
	*p = x
	return p
}

func (x Reset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reset) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_pbauth_auth_proto_enumTypes[2].Descriptor()
}

func (Reset) Type() protoreflect.EnumType {
	return &file_server_proto_pbauth_auth_proto_enumTypes[2]
}

func (x Reset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reset.Descriptor instead.
func (Reset) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_pbauth_auth_proto_rawDescGZIP(), []int{2}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Secure   string `protobuf:"bytes,4,opt,name=secure,proto3" json:"secure,omitempty"`
	Refresh  string `protobuf:"bytes,5,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Signup   Signup `protobuf:"varint,6,opt,name=signup,proto3,enum=pbauth.Signup" json:"signup,omitempty"`
	Signin   Signin `protobuf:"varint,7,opt,name=signin,proto3,enum=pbauth.Signin" json:"signin,omitempty"`
	Reset_   Reset  `protobuf:"varint,8,opt,name=reset,proto3,enum=pbauth.Reset" json:"reset,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbauth_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbauth_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_server_proto_pbauth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Request) GetSecure() string {
	if x != nil {
		return x.Secure
	}
	return ""
}

func (x *Request) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

func (x *Request) GetSignup() Signup {
	if x != nil {
		return x.Signup
	}
	return Signup_ActionSignupAccount
}

func (x *Request) GetSignin() Signin {
	if x != nil {
		return x.Signin
	}
	return Signin_ActionSigninAccount
}

func (x *Request) GetReset_() Reset {
	if x != nil {
		return x.Reset_
	}
	return Reset_ActionResetAccount
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessToken  string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbauth_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbauth_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_server_proto_pbauth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Response) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type Response_Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Subject     int64  `protobuf:"varint,2,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *Response_Session) Reset() {
	*x = Response_Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbauth_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Session) ProtoMessage() {}

func (x *Response_Session) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbauth_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Session.ProtoReflect.Descriptor instead.
func (*Response_Session) Descriptor() ([]byte, []int) {
	return file_server_proto_pbauth_auth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Response_Session) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Response_Session) GetSubject() int64 {
	if x != nil {
		return x.Subject
	}
	return 0
}

var File_server_proto_pbauth_auth_proto protoreflect.FileDescriptor

var file_server_proto_pbauth_auth_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x69,
	0x67, 0x6e, 0x75, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x75, 0x70, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x69, 0x6e, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x05, 0x72, 0x65,
	0x73, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x22,
	0xaa, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x46, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2a, 0x50, 0x0a, 0x06,
	0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x43,
	0x6f, 0x64, 0x65, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x69, 0x67, 0x6e, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x02, 0x2a, 0x50,
	0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x69,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x02,
	0x2a, 0x65, 0x0a, 0x05, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x02, 0x12, 0x17,
	0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x10, 0x03, 0x32, 0xa7, 0x03, 0x0a, 0x03, 0x41, 0x70, 0x69, 0x12,
	0x54, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12,
	0x0f, 0x2e, 0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x76, 0x32, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x69, 0x67, 0x6e,
	0x75, 0x70, 0x3a, 0x01, 0x2a, 0x12, 0x54, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b,
	0x22, 0x16, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2d, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x52, 0x0a, 0x0b, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22, 0x15, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x72, 0x65, 0x73, 0x65, 0x74, 0x3a, 0x01, 0x2a, 0x12,
	0x4e, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x0f, 0x2e, 0x70,
	0x62, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x13, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x2f, 0x73, 0x65, 0x74, 0x2d, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x3a, 0x01, 0x2a, 0x12,
	0x50, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x0f, 0x2e,
	0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x22, 0x14, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x2f, 0x67, 0x65, 0x74, 0x2d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x3a, 0x01,
	0x2a, 0x42, 0x15, 0x5a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_proto_pbauth_auth_proto_rawDescOnce sync.Once
	file_server_proto_pbauth_auth_proto_rawDescData = file_server_proto_pbauth_auth_proto_rawDesc
)

func file_server_proto_pbauth_auth_proto_rawDescGZIP() []byte {
	file_server_proto_pbauth_auth_proto_rawDescOnce.Do(func() {
		file_server_proto_pbauth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_pbauth_auth_proto_rawDescData)
	})
	return file_server_proto_pbauth_auth_proto_rawDescData
}

var file_server_proto_pbauth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_server_proto_pbauth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_proto_pbauth_auth_proto_goTypes = []interface{}{
	(Signup)(0),              // 0: pbauth.Signup
	(Signin)(0),              // 1: pbauth.Signin
	(Reset)(0),               // 2: pbauth.Reset
	(*Request)(nil),          // 3: pbauth.Request
	(*Response)(nil),         // 4: pbauth.Response
	(*Response_Session)(nil), // 5: pbauth.Response.Session
}
var file_server_proto_pbauth_auth_proto_depIdxs = []int32{
	0, // 0: pbauth.Request.signup:type_name -> pbauth.Signup
	1, // 1: pbauth.Request.signin:type_name -> pbauth.Signin
	2, // 2: pbauth.Request.reset:type_name -> pbauth.Reset
	3, // 3: pbauth.Api.ActionSignup:input_type -> pbauth.Request
	3, // 4: pbauth.Api.ActionSignin:input_type -> pbauth.Request
	3, // 5: pbauth.Api.ActionReset:input_type -> pbauth.Request
	3, // 6: pbauth.Api.SetLogout:input_type -> pbauth.Request
	3, // 7: pbauth.Api.GetRefresh:input_type -> pbauth.Request
	4, // 8: pbauth.Api.ActionSignup:output_type -> pbauth.Response
	4, // 9: pbauth.Api.ActionSignin:output_type -> pbauth.Response
	4, // 10: pbauth.Api.ActionReset:output_type -> pbauth.Response
	4, // 11: pbauth.Api.SetLogout:output_type -> pbauth.Response
	4, // 12: pbauth.Api.GetRefresh:output_type -> pbauth.Response
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_server_proto_pbauth_auth_proto_init() }
func file_server_proto_pbauth_auth_proto_init() {
	if File_server_proto_pbauth_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_proto_pbauth_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbauth_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbauth_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_pbauth_auth_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_pbauth_auth_proto_goTypes,
		DependencyIndexes: file_server_proto_pbauth_auth_proto_depIdxs,
		EnumInfos:         file_server_proto_pbauth_auth_proto_enumTypes,
		MessageInfos:      file_server_proto_pbauth_auth_proto_msgTypes,
	}.Build()
	File_server_proto_pbauth_auth_proto = out.File
	file_server_proto_pbauth_auth_proto_rawDesc = nil
	file_server_proto_pbauth_auth_proto_goTypes = nil
	file_server_proto_pbauth_auth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	// Account action signup.
	ActionSignup(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Account action signin.
	ActionSignin(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Account action reset.
	ActionReset(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Account set logout.
	SetLogout(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// Account get refresh.
	GetRefresh(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) ActionSignup(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbauth.Api/ActionSignup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ActionSignin(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbauth.Api/ActionSignin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ActionReset(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbauth.Api/ActionReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SetLogout(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbauth.Api/SetLogout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetRefresh(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbauth.Api/GetRefresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	// Account action signup.
	ActionSignup(context.Context, *Request) (*Response, error)
	// Account action signin.
	ActionSignin(context.Context, *Request) (*Response, error)
	// Account action reset.
	ActionReset(context.Context, *Request) (*Response, error)
	// Account set logout.
	SetLogout(context.Context, *Request) (*Response, error)
	// Account get refresh.
	GetRefresh(context.Context, *Request) (*Response, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) ActionSignup(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionSignup not implemented")
}
func (*UnimplementedApiServer) ActionSignin(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionSignin not implemented")
}
func (*UnimplementedApiServer) ActionReset(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionReset not implemented")
}
func (*UnimplementedApiServer) SetLogout(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogout not implemented")
}
func (*UnimplementedApiServer) GetRefresh(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRefresh not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_ActionSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ActionSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbauth.Api/ActionSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ActionSignup(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ActionSignin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ActionSignin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbauth.Api/ActionSignin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ActionSignin(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ActionReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ActionReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbauth.Api/ActionReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ActionReset(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SetLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SetLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbauth.Api/SetLogout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SetLogout(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbauth.Api/GetRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetRefresh(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbauth.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActionSignup",
			Handler:    _Api_ActionSignup_Handler,
		},
		{
			MethodName: "ActionSignin",
			Handler:    _Api_ActionSignin_Handler,
		},
		{
			MethodName: "ActionReset",
			Handler:    _Api_ActionReset_Handler,
		},
		{
			MethodName: "SetLogout",
			Handler:    _Api_SetLogout_Handler,
		},
		{
			MethodName: "GetRefresh",
			Handler:    _Api_GetRefresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/pbauth/auth.proto",
}
