version: '3'
#
services:
  server:
    restart: always
    build: .
    depends_on:
      - pg
      - rabbit
      - redis
    environment:
      - POSTGRES_CONNECTION=postgres://postgres:123123@pg/envoys?sslmode=disable
    volumes:
      - ./config.json:/app/config.json
    ports:
      - 3082:3082
  pg:
    user: postgres
    build:
      context: .
      dockerfile: ./Dockerfile.PostgreSQL
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_USER=envoys
    ports:
      - 53:53
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./data/pg:/home/postgres/pgdata/data
  
  rabbit:
    build:
      context: .
      dockerfile: ./Dockerfile.RabbitMQ
    ports:
      - 15675:15675
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq

  redis:
    build:
      context: .
      dockerfile: ./Dockerfile.Redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data