FROM rabbitmq:3.8-management
RUN rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_web_stomp rabbitmq_web_mqtt rabbitmq_shovel rabbitmq_shovel_management

COPY ./rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
