// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: server/proto/pbindex/index.proto

package pbindex

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Statistic message structure.
type Statistic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accounts     *Statistic_Account     `protobuf:"bytes,1,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Chains       *Statistic_Chain       `protobuf:"bytes,2,opt,name=chains,proto3" json:"chains,omitempty"`
	Currencies   *Statistic_Currency    `protobuf:"bytes,3,opt,name=currencies,proto3" json:"currencies,omitempty"`
	Pairs        *Statistic_Pair        `protobuf:"bytes,4,opt,name=pairs,proto3" json:"pairs,omitempty"`
	Transactions *Statistic_Transaction `protobuf:"bytes,5,opt,name=transactions,proto3" json:"transactions,omitempty"`
	Orders       *Statistic_Order       `protobuf:"bytes,6,opt,name=orders,proto3" json:"orders,omitempty"`
	Reserves     []*Statistic_Reserve   `protobuf:"bytes,7,rep,name=reserves,proto3" json:"reserves,omitempty"`
}

func (x *Statistic) Reset() {
	*x = Statistic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic) ProtoMessage() {}

func (x *Statistic) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic.ProtoReflect.Descriptor instead.
func (*Statistic) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{0}
}

func (x *Statistic) GetAccounts() *Statistic_Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *Statistic) GetChains() *Statistic_Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *Statistic) GetCurrencies() *Statistic_Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *Statistic) GetPairs() *Statistic_Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *Statistic) GetTransactions() *Statistic_Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Statistic) GetOrders() *Statistic_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Statistic) GetReserves() []*Statistic_Reserve {
	if x != nil {
		return x.Reserves
	}
	return nil
}

// Pair message structure.
type Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol    string  `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseUnit  string  `protobuf:"bytes,3,opt,name=base_unit,json=baseUnit,proto3" json:"base_unit,omitempty"`
	QuoteUnit string  `protobuf:"bytes,4,opt,name=quote_unit,json=quoteUnit,proto3" json:"quote_unit,omitempty"`
	Price     float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Ratio     float64 `protobuf:"fixed64,6,opt,name=ratio,proto3" json:"ratio,omitempty"`
}

func (x *Pair) Reset() {
	*x = Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{1}
}

func (x *Pair) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pair) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Pair) GetBaseUnit() string {
	if x != nil {
		return x.BaseUnit
	}
	return ""
}

func (x *Pair) GetQuoteUnit() string {
	if x != nil {
		return x.QuoteUnit
	}
	return ""
}

func (x *Pair) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Pair) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

// Currency message structure.
type Currency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol       string  `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	FeesTrade    float64 `protobuf:"fixed64,4,opt,name=fees_trade,json=feesTrade,proto3" json:"fees_trade,omitempty"`
	FeesDiscount float64 `protobuf:"fixed64,5,opt,name=fees_discount,json=feesDiscount,proto3" json:"fees_discount,omitempty"`
	Pairs        []*Pair `protobuf:"bytes,6,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *Currency) Reset() {
	*x = Currency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{2}
}

func (x *Currency) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Currency) GetFeesTrade() float64 {
	if x != nil {
		return x.FeesTrade
	}
	return 0
}

func (x *Currency) GetFeesDiscount() float64 {
	if x != nil {
		return x.FeesDiscount
	}
	return 0
}

func (x *Currency) GetPairs() []*Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

// Statistic structure.
type GetRequestStatistic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRequestStatistic) Reset() {
	*x = GetRequestStatistic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestStatistic) ProtoMessage() {}

func (x *GetRequestStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestStatistic.ProtoReflect.Descriptor instead.
func (*GetRequestStatistic) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{3}
}

type ResponseStatistic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields *Statistic `protobuf:"bytes,1,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ResponseStatistic) Reset() {
	*x = ResponseStatistic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatistic) ProtoMessage() {}

func (x *ResponseStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatistic.ProtoReflect.Descriptor instead.
func (*ResponseStatistic) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseStatistic) GetFields() *Statistic {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Currency structure.
type GetRequestCurrencies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequestCurrencies) Reset() {
	*x = GetRequestCurrencies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestCurrencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestCurrencies) ProtoMessage() {}

func (x *GetRequestCurrencies) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestCurrencies.ProtoReflect.Descriptor instead.
func (*GetRequestCurrencies) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequestCurrencies) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResponseCurrency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*Currency `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Count  int32       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ResponseCurrency) Reset() {
	*x = ResponseCurrency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCurrency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCurrency) ProtoMessage() {}

func (x *ResponseCurrency) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCurrency.ProtoReflect.Descriptor instead.
func (*ResponseCurrency) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseCurrency) GetFields() []*Currency {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ResponseCurrency) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Pair structure.
type GetRequestPairs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRequestPairs) Reset() {
	*x = GetRequestPairs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestPairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestPairs) ProtoMessage() {}

func (x *GetRequestPairs) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestPairs.ProtoReflect.Descriptor instead.
func (*GetRequestPairs) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{7}
}

type ResponsePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*Pair `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ResponsePair) Reset() {
	*x = ResponsePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePair) ProtoMessage() {}

func (x *ResponsePair) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePair.ProtoReflect.Descriptor instead.
func (*ResponsePair) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{8}
}

func (x *ResponsePair) GetFields() []*Pair {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Statistic_Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable int32 `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Enable  int32 `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Statistic_Account) Reset() {
	*x = Statistic_Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Account) ProtoMessage() {}

func (x *Statistic_Account) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Account.ProtoReflect.Descriptor instead.
func (*Statistic_Account) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Statistic_Account) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

func (x *Statistic_Account) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type Statistic_Chain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable int32 `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Enable  int32 `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Statistic_Chain) Reset() {
	*x = Statistic_Chain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Chain) ProtoMessage() {}

func (x *Statistic_Chain) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Chain.ProtoReflect.Descriptor instead.
func (*Statistic_Chain) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Statistic_Chain) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

func (x *Statistic_Chain) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type Statistic_Currency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable int32 `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Enable  int32 `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Statistic_Currency) Reset() {
	*x = Statistic_Currency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Currency) ProtoMessage() {}

func (x *Statistic_Currency) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Currency.ProtoReflect.Descriptor instead.
func (*Statistic_Currency) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Statistic_Currency) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

func (x *Statistic_Currency) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type Statistic_Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable int32 `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Enable  int32 `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Statistic_Pair) Reset() {
	*x = Statistic_Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Pair) ProtoMessage() {}

func (x *Statistic_Pair) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Pair.ProtoReflect.Descriptor instead.
func (*Statistic_Pair) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Statistic_Pair) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

func (x *Statistic_Pair) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type Statistic_Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filled  int32 `protobuf:"varint,1,opt,name=filled,proto3" json:"filled,omitempty"`
	Pending int32 `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
}

func (x *Statistic_Transaction) Reset() {
	*x = Statistic_Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Transaction) ProtoMessage() {}

func (x *Statistic_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Transaction.ProtoReflect.Descriptor instead.
func (*Statistic_Transaction) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Statistic_Transaction) GetFilled() int32 {
	if x != nil {
		return x.Filled
	}
	return 0
}

func (x *Statistic_Transaction) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type Statistic_Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buy  int32 `protobuf:"varint,1,opt,name=buy,proto3" json:"buy,omitempty"`
	Sell int32 `protobuf:"varint,2,opt,name=sell,proto3" json:"sell,omitempty"`
}

func (x *Statistic_Order) Reset() {
	*x = Statistic_Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Order) ProtoMessage() {}

func (x *Statistic_Order) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Order.ProtoReflect.Descriptor instead.
func (*Statistic_Order) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Statistic_Order) GetBuy() int32 {
	if x != nil {
		return x.Buy
	}
	return 0
}

func (x *Statistic_Order) GetSell() int32 {
	if x != nil {
		return x.Sell
	}
	return 0
}

type Statistic_Reserve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol              string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Value               float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueCharged        float64 `protobuf:"fixed64,3,opt,name=value_charged,json=valueCharged,proto3" json:"value_charged,omitempty"`
	ValueChargedConvert float64 `protobuf:"fixed64,4,opt,name=value_charged_convert,json=valueChargedConvert,proto3" json:"value_charged_convert,omitempty"`
	ValueCosts          float64 `protobuf:"fixed64,5,opt,name=value_costs,json=valueCosts,proto3" json:"value_costs,omitempty"`
}

func (x *Statistic_Reserve) Reset() {
	*x = Statistic_Reserve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_pbindex_index_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Reserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Reserve) ProtoMessage() {}

func (x *Statistic_Reserve) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_pbindex_index_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Reserve.ProtoReflect.Descriptor instead.
func (*Statistic_Reserve) Descriptor() ([]byte, []int) {
	return file_server_proto_pbindex_index_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Statistic_Reserve) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Statistic_Reserve) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Statistic_Reserve) GetValueCharged() float64 {
	if x != nil {
		return x.ValueCharged
	}
	return 0
}

func (x *Statistic_Reserve) GetValueChargedConvert() float64 {
	if x != nil {
		return x.ValueChargedConvert
	}
	return 0
}

func (x *Statistic_Reserve) GetValueCosts() float64 {
	if x != nil {
		return x.ValueCosts
	}
	return 0
}

var File_server_proto_pbindex_index_proto protoreflect.FileDescriptor

var file_server_proto_pbindex_index_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x07, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x36, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12,
	0x30, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x06, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x73, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x2d,
	0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x12, 0x42, 0x0a,
	0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x30, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x1a, 0x3b, 0x0a, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x39, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x1a, 0x3c, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x1a, 0x38, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x3f, 0x0a, 0x0b, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69,
	0x6c, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x6c,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x1a, 0x2d, 0x0a, 0x05,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x62, 0x75, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x6c, 0x1a, 0xb1, 0x01, 0x0a, 0x07,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x13, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x73, 0x22,
	0x96, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x22, 0xaf, 0x01, 0x0a, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x65, 0x65, 0x73, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x66, 0x65, 0x65, 0x73, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x66, 0x65, 0x65, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x66, 0x65, 0x65, 0x73, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x50,
	0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x22, 0x3f, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x2a, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x10, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x29,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x69,
	0x72, 0x73, 0x22, 0x35, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61,
	0x69, 0x72, 0x12, 0x25, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x32, 0xbd, 0x02, 0x0a, 0x03, 0x41, 0x70,
	0x69, 0x12, 0x69, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x1a,
	0x1a, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x22, 0x1f, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x19, 0x12, 0x17, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x67,
	0x65, 0x74, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x6e, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x2e,
	0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x1a, 0x19, 0x2e, 0x70,
	0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22,
	0x18, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x67, 0x65, 0x74, 0x2d, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x5b, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x69,
	0x72, 0x73, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x18, 0x22, 0x13, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x67, 0x65, 0x74,
	0x2d, 0x70, 0x61, 0x69, 0x72, 0x73, 0x3a, 0x01, 0x2a, 0x42, 0x16, 0x5a, 0x14, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_proto_pbindex_index_proto_rawDescOnce sync.Once
	file_server_proto_pbindex_index_proto_rawDescData = file_server_proto_pbindex_index_proto_rawDesc
)

func file_server_proto_pbindex_index_proto_rawDescGZIP() []byte {
	file_server_proto_pbindex_index_proto_rawDescOnce.Do(func() {
		file_server_proto_pbindex_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_pbindex_index_proto_rawDescData)
	})
	return file_server_proto_pbindex_index_proto_rawDescData
}

var file_server_proto_pbindex_index_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_server_proto_pbindex_index_proto_goTypes = []interface{}{
	(*Statistic)(nil),             // 0: pbindex.Statistic
	(*Pair)(nil),                  // 1: pbindex.Pair
	(*Currency)(nil),              // 2: pbindex.Currency
	(*GetRequestStatistic)(nil),   // 3: pbindex.GetRequestStatistic
	(*ResponseStatistic)(nil),     // 4: pbindex.ResponseStatistic
	(*GetRequestCurrencies)(nil),  // 5: pbindex.GetRequestCurrencies
	(*ResponseCurrency)(nil),      // 6: pbindex.ResponseCurrency
	(*GetRequestPairs)(nil),       // 7: pbindex.GetRequestPairs
	(*ResponsePair)(nil),          // 8: pbindex.ResponsePair
	(*Statistic_Account)(nil),     // 9: pbindex.Statistic.Account
	(*Statistic_Chain)(nil),       // 10: pbindex.Statistic.Chain
	(*Statistic_Currency)(nil),    // 11: pbindex.Statistic.Currency
	(*Statistic_Pair)(nil),        // 12: pbindex.Statistic.Pair
	(*Statistic_Transaction)(nil), // 13: pbindex.Statistic.Transaction
	(*Statistic_Order)(nil),       // 14: pbindex.Statistic.Order
	(*Statistic_Reserve)(nil),     // 15: pbindex.Statistic.Reserve
}
var file_server_proto_pbindex_index_proto_depIdxs = []int32{
	9,  // 0: pbindex.Statistic.accounts:type_name -> pbindex.Statistic.Account
	10, // 1: pbindex.Statistic.chains:type_name -> pbindex.Statistic.Chain
	11, // 2: pbindex.Statistic.currencies:type_name -> pbindex.Statistic.Currency
	12, // 3: pbindex.Statistic.pairs:type_name -> pbindex.Statistic.Pair
	13, // 4: pbindex.Statistic.transactions:type_name -> pbindex.Statistic.Transaction
	14, // 5: pbindex.Statistic.orders:type_name -> pbindex.Statistic.Order
	15, // 6: pbindex.Statistic.reserves:type_name -> pbindex.Statistic.Reserve
	1,  // 7: pbindex.Currency.pairs:type_name -> pbindex.Pair
	0,  // 8: pbindex.ResponseStatistic.fields:type_name -> pbindex.Statistic
	2,  // 9: pbindex.ResponseCurrency.fields:type_name -> pbindex.Currency
	1,  // 10: pbindex.ResponsePair.fields:type_name -> pbindex.Pair
	3,  // 11: pbindex.Api.GetStatistic:input_type -> pbindex.GetRequestStatistic
	5,  // 12: pbindex.Api.GetCurrencies:input_type -> pbindex.GetRequestCurrencies
	7,  // 13: pbindex.Api.GetPairs:input_type -> pbindex.GetRequestPairs
	4,  // 14: pbindex.Api.GetStatistic:output_type -> pbindex.ResponseStatistic
	6,  // 15: pbindex.Api.GetCurrencies:output_type -> pbindex.ResponseCurrency
	8,  // 16: pbindex.Api.GetPairs:output_type -> pbindex.ResponsePair
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_server_proto_pbindex_index_proto_init() }
func file_server_proto_pbindex_index_proto_init() {
	if File_server_proto_pbindex_index_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_proto_pbindex_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Currency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestStatistic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStatistic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestCurrencies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCurrency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestPairs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Chain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Currency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_pbindex_index_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Reserve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_pbindex_index_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_pbindex_index_proto_goTypes,
		DependencyIndexes: file_server_proto_pbindex_index_proto_depIdxs,
		MessageInfos:      file_server_proto_pbindex_index_proto_msgTypes,
	}.Build()
	File_server_proto_pbindex_index_proto = out.File
	file_server_proto_pbindex_index_proto_rawDesc = nil
	file_server_proto_pbindex_index_proto_goTypes = nil
	file_server_proto_pbindex_index_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	// Get statistic.
	GetStatistic(ctx context.Context, in *GetRequestStatistic, opts ...grpc.CallOption) (*ResponseStatistic, error)
	// Index get currencies.
	GetCurrencies(ctx context.Context, in *GetRequestCurrencies, opts ...grpc.CallOption) (*ResponseCurrency, error)
	// Index get pairs.
	GetPairs(ctx context.Context, in *GetRequestPairs, opts ...grpc.CallOption) (*ResponsePair, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) GetStatistic(ctx context.Context, in *GetRequestStatistic, opts ...grpc.CallOption) (*ResponseStatistic, error) {
	out := new(ResponseStatistic)
	err := c.cc.Invoke(ctx, "/pbindex.Api/GetStatistic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetCurrencies(ctx context.Context, in *GetRequestCurrencies, opts ...grpc.CallOption) (*ResponseCurrency, error) {
	out := new(ResponseCurrency)
	err := c.cc.Invoke(ctx, "/pbindex.Api/GetCurrencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetPairs(ctx context.Context, in *GetRequestPairs, opts ...grpc.CallOption) (*ResponsePair, error) {
	out := new(ResponsePair)
	err := c.cc.Invoke(ctx, "/pbindex.Api/GetPairs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	// Get statistic.
	GetStatistic(context.Context, *GetRequestStatistic) (*ResponseStatistic, error)
	// Index get currencies.
	GetCurrencies(context.Context, *GetRequestCurrencies) (*ResponseCurrency, error)
	// Index get pairs.
	GetPairs(context.Context, *GetRequestPairs) (*ResponsePair, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) GetStatistic(context.Context, *GetRequestStatistic) (*ResponseStatistic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistic not implemented")
}
func (*UnimplementedApiServer) GetCurrencies(context.Context, *GetRequestCurrencies) (*ResponseCurrency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrencies not implemented")
}
func (*UnimplementedApiServer) GetPairs(context.Context, *GetRequestPairs) (*ResponsePair, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPairs not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_GetStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestStatistic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbindex.Api/GetStatistic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetStatistic(ctx, req.(*GetRequestStatistic))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestCurrencies)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbindex.Api/GetCurrencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetCurrencies(ctx, req.(*GetRequestCurrencies))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestPairs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbindex.Api/GetPairs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetPairs(ctx, req.(*GetRequestPairs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbindex.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatistic",
			Handler:    _Api_GetStatistic_Handler,
		},
		{
			MethodName: "GetCurrencies",
			Handler:    _Api_GetCurrencies_Handler,
		},
		{
			MethodName: "GetPairs",
			Handler:    _Api_GetPairs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/pbindex/index.proto",
}
