// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: server/proto/pbstock/stock.proto

package pbstock

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_server_proto_pbstock_stock_proto protoreflect.FileDescriptor

var file_server_proto_pbstock_stock_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x32, 0x06, 0x0a, 0x04, 0x53,
	0x70, 0x6f, 0x74, 0x42, 0x16, 0x5a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var file_server_proto_pbstock_stock_proto_goTypes = []interface{}{}
var file_server_proto_pbstock_stock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_proto_pbstock_stock_proto_init() }
func file_server_proto_pbstock_stock_proto_init() {
	if File_server_proto_pbstock_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_pbstock_stock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_pbstock_stock_proto_goTypes,
		DependencyIndexes: file_server_proto_pbstock_stock_proto_depIdxs,
	}.Build()
	File_server_proto_pbstock_stock_proto = out.File
	file_server_proto_pbstock_stock_proto_rawDesc = nil
	file_server_proto_pbstock_stock_proto_goTypes = nil
	file_server_proto_pbstock_stock_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SpotClient is the client API for Spot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpotClient interface {
}

type spotClient struct {
	cc grpc.ClientConnInterface
}

func NewSpotClient(cc grpc.ClientConnInterface) SpotClient {
	return &spotClient{cc}
}

// SpotServer is the server API for Spot service.
type SpotServer interface {
}

// UnimplementedSpotServer can be embedded to have forward compatible implementations.
type UnimplementedSpotServer struct {
}

func RegisterSpotServer(s *grpc.Server, srv SpotServer) {
	s.RegisterService(&_Spot_serviceDesc, srv)
}

var _Spot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbstock.Spot",
	HandlerType: (*SpotServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "server/proto/pbstock/stock.proto",
}
