// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: server/proto/auth.proto

package proto

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signup int32

const (
	Signup_ActionSignupAccount Signup = 0
	Signup_ActionSignupCode    Signup = 1
	Signup_ActionSignupConfirm Signup = 2
)

// Enum value maps for Signup.
var (
	Signup_name = map[int32]string{
		0: "ActionSignupAccount",
		1: "ActionSignupCode",
		2: "ActionSignupConfirm",
	}
	Signup_value = map[string]int32{
		"ActionSignupAccount": 0,
		"ActionSignupCode":    1,
		"ActionSignupConfirm": 2,
	}
)

func (x Signup) Enum() *Signup {
	p := new(Signup)
	*p = x
	return p
}

func (x Signup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signup) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_auth_proto_enumTypes[0].Descriptor()
}

func (Signup) Type() protoreflect.EnumType {
	return &file_server_proto_auth_proto_enumTypes[0]
}

func (x Signup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signup.Descriptor instead.
func (Signup) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_auth_proto_rawDescGZIP(), []int{0}
}

type Signin int32

const (
	Signin_ActionSigninAccount Signin = 0
	Signin_ActionSigninCode    Signin = 1
	Signin_ActionSigninConfirm Signin = 2
)

// Enum value maps for Signin.
var (
	Signin_name = map[int32]string{
		0: "ActionSigninAccount",
		1: "ActionSigninCode",
		2: "ActionSigninConfirm",
	}
	Signin_value = map[string]int32{
		"ActionSigninAccount": 0,
		"ActionSigninCode":    1,
		"ActionSigninConfirm": 2,
	}
)

func (x Signin) Enum() *Signin {
	p := new(Signin)
	*p = x
	return p
}

func (x Signin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signin) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_auth_proto_enumTypes[1].Descriptor()
}

func (Signin) Type() protoreflect.EnumType {
	return &file_server_proto_auth_proto_enumTypes[1]
}

func (x Signin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signin.Descriptor instead.
func (Signin) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_auth_proto_rawDescGZIP(), []int{1}
}

type Reset int32

const (
	Reset_ActionResetAccount  Reset = 0
	Reset_ActionResetCode     Reset = 1
	Reset_ActionResetConfirm  Reset = 2
	Reset_ActionResetPassword Reset = 3
)

// Enum value maps for Reset.
var (
	Reset_name = map[int32]string{
		0: "ActionResetAccount",
		1: "ActionResetCode",
		2: "ActionResetConfirm",
		3: "ActionResetPassword",
	}
	Reset_value = map[string]int32{
		"ActionResetAccount":  0,
		"ActionResetCode":     1,
		"ActionResetConfirm":  2,
		"ActionResetPassword": 3,
	}
)

func (x Reset) Enum() *Reset {
	p := new(Reset)
	*p = x
	return p
}

func (x Reset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reset) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_auth_proto_enumTypes[2].Descriptor()
}

func (Reset) Type() protoreflect.EnumType {
	return &file_server_proto_auth_proto_enumTypes[2]
}

func (x Reset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reset.Descriptor instead.
func (Reset) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_auth_proto_rawDescGZIP(), []int{2}
}

type RequestAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Secure   string `protobuf:"bytes,4,opt,name=secure,proto3" json:"secure,omitempty"`
	Refresh  string `protobuf:"bytes,5,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Signup   Signup `protobuf:"varint,6,opt,name=signup,proto3,enum=proto.Signup" json:"signup,omitempty"`
	Signin   Signin `protobuf:"varint,7,opt,name=signin,proto3,enum=proto.Signin" json:"signin,omitempty"`
	Reset_   Reset  `protobuf:"varint,8,opt,name=reset,proto3,enum=proto.Reset" json:"reset,omitempty"`
}

func (x *RequestAuth) Reset() {
	*x = RequestAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAuth) ProtoMessage() {}

func (x *RequestAuth) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAuth.ProtoReflect.Descriptor instead.
func (*RequestAuth) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAuth) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RequestAuth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RequestAuth) GetSecure() string {
	if x != nil {
		return x.Secure
	}
	return ""
}

func (x *RequestAuth) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

func (x *RequestAuth) GetSignup() Signup {
	if x != nil {
		return x.Signup
	}
	return Signup_ActionSignupAccount
}

func (x *RequestAuth) GetSignin() Signin {
	if x != nil {
		return x.Signin
	}
	return Signin_ActionSigninAccount
}

func (x *RequestAuth) GetReset_() Reset {
	if x != nil {
		return x.Reset_
	}
	return Reset_ActionResetAccount
}

type ResponseAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessToken  string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *ResponseAuth) Reset() {
	*x = ResponseAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAuth) ProtoMessage() {}

func (x *ResponseAuth) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAuth.ProtoReflect.Descriptor instead.
func (*ResponseAuth) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAuth) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseAuth) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ResponseAuth) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ResponseAuth_Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Subject     int64  `protobuf:"varint,2,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *ResponseAuth_Session) Reset() {
	*x = ResponseAuth_Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAuth_Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAuth_Session) ProtoMessage() {}

func (x *ResponseAuth_Session) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAuth_Session.ProtoReflect.Descriptor instead.
func (*ResponseAuth_Session) Descriptor() ([]byte, []int) {
	return file_server_proto_auth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResponseAuth_Session) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ResponseAuth_Session) GetSubject() int64 {
	if x != nil {
		return x.Subject
	}
	return 0
}

var File_server_proto_auth_proto protoreflect.FileDescriptor

var file_server_proto_auth_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7,
	0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x75, 0x74, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x75, 0x70, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x25, 0x0a,
	0x06, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x52, 0x06, 0x73, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x52, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x22, 0xae, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x75, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x1a, 0x46, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2a, 0x50, 0x0a, 0x06, 0x53, 0x69, 0x67,
	0x6e, 0x75, 0x70, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67,
	0x6e, 0x75, 0x70, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e,
	0x75, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x02, 0x2a, 0x50, 0x0a, 0x06, 0x53,
	0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x69, 0x67, 0x6e, 0x69, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69,
	0x67, 0x6e, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x02, 0x2a, 0x65, 0x0a,
	0x05, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x10, 0x03, 0x32, 0xc6, 0x03, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x5a, 0x0a,
	0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x75, 0x74,
	0x68, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x41, 0x75, 0x74, 0x68, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16,
	0x2f, 0x76, 0x32, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d,
	0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x3a, 0x01, 0x2a, 0x12, 0x5a, 0x0a, 0x0c, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x75, 0x74, 0x68, 0x1a, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x75,
	0x74, 0x68, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x76, 0x32, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x69, 0x67, 0x6e,
	0x69, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x58, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x41, 0x75, 0x74, 0x68, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x75, 0x74, 0x68, 0x22, 0x20, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22, 0x15, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x72, 0x65, 0x73, 0x65, 0x74, 0x3a, 0x01, 0x2a, 0x12,
	0x54, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x75, 0x74, 0x68,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x41, 0x75, 0x74, 0x68, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x13, 0x2f,
	0x76, 0x32, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x73, 0x65, 0x74, 0x2d, 0x6c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x56, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x41, 0x75, 0x74, 0x68, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x75, 0x74, 0x68, 0x22, 0x1f, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x19, 0x22, 0x14, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x67,
	0x65, 0x74, 0x2d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x3a, 0x01, 0x2a, 0x42, 0x0e, 0x5a,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_proto_auth_proto_rawDescOnce sync.Once
	file_server_proto_auth_proto_rawDescData = file_server_proto_auth_proto_rawDesc
)

func file_server_proto_auth_proto_rawDescGZIP() []byte {
	file_server_proto_auth_proto_rawDescOnce.Do(func() {
		file_server_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_auth_proto_rawDescData)
	})
	return file_server_proto_auth_proto_rawDescData
}

var file_server_proto_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_server_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_proto_auth_proto_goTypes = []interface{}{
	(Signup)(0),                  // 0: proto.Signup
	(Signin)(0),                  // 1: proto.Signin
	(Reset)(0),                   // 2: proto.Reset
	(*RequestAuth)(nil),          // 3: proto.RequestAuth
	(*ResponseAuth)(nil),         // 4: proto.ResponseAuth
	(*ResponseAuth_Session)(nil), // 5: proto.ResponseAuth.Session
}
var file_server_proto_auth_proto_depIdxs = []int32{
	0, // 0: proto.RequestAuth.signup:type_name -> proto.Signup
	1, // 1: proto.RequestAuth.signin:type_name -> proto.Signin
	2, // 2: proto.RequestAuth.reset:type_name -> proto.Reset
	3, // 3: proto.Auth.ActionSignup:input_type -> proto.RequestAuth
	3, // 4: proto.Auth.ActionSignin:input_type -> proto.RequestAuth
	3, // 5: proto.Auth.ActionReset:input_type -> proto.RequestAuth
	3, // 6: proto.Auth.SetLogout:input_type -> proto.RequestAuth
	3, // 7: proto.Auth.GetRefresh:input_type -> proto.RequestAuth
	4, // 8: proto.Auth.ActionSignup:output_type -> proto.ResponseAuth
	4, // 9: proto.Auth.ActionSignin:output_type -> proto.ResponseAuth
	4, // 10: proto.Auth.ActionReset:output_type -> proto.ResponseAuth
	4, // 11: proto.Auth.SetLogout:output_type -> proto.ResponseAuth
	4, // 12: proto.Auth.GetRefresh:output_type -> proto.ResponseAuth
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_server_proto_auth_proto_init() }
func file_server_proto_auth_proto_init() {
	if File_server_proto_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_proto_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAuth_Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_auth_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_auth_proto_goTypes,
		DependencyIndexes: file_server_proto_auth_proto_depIdxs,
		EnumInfos:         file_server_proto_auth_proto_enumTypes,
		MessageInfos:      file_server_proto_auth_proto_msgTypes,
	}.Build()
	File_server_proto_auth_proto = out.File
	file_server_proto_auth_proto_rawDesc = nil
	file_server_proto_auth_proto_goTypes = nil
	file_server_proto_auth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	// Account action signup.
	ActionSignup(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error)
	// Account action signin.
	ActionSignin(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error)
	// Account action reset.
	ActionReset(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error)
	// Account set logout.
	SetLogout(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error)
	// Account get refresh.
	GetRefresh(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) ActionSignup(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error) {
	out := new(ResponseAuth)
	err := c.cc.Invoke(ctx, "/proto.Auth/ActionSignup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ActionSignin(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error) {
	out := new(ResponseAuth)
	err := c.cc.Invoke(ctx, "/proto.Auth/ActionSignin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ActionReset(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error) {
	out := new(ResponseAuth)
	err := c.cc.Invoke(ctx, "/proto.Auth/ActionReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SetLogout(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error) {
	out := new(ResponseAuth)
	err := c.cc.Invoke(ctx, "/proto.Auth/SetLogout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetRefresh(ctx context.Context, in *RequestAuth, opts ...grpc.CallOption) (*ResponseAuth, error) {
	out := new(ResponseAuth)
	err := c.cc.Invoke(ctx, "/proto.Auth/GetRefresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	// Account action signup.
	ActionSignup(context.Context, *RequestAuth) (*ResponseAuth, error)
	// Account action signin.
	ActionSignin(context.Context, *RequestAuth) (*ResponseAuth, error)
	// Account action reset.
	ActionReset(context.Context, *RequestAuth) (*ResponseAuth, error)
	// Account set logout.
	SetLogout(context.Context, *RequestAuth) (*ResponseAuth, error)
	// Account get refresh.
	GetRefresh(context.Context, *RequestAuth) (*ResponseAuth, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) ActionSignup(context.Context, *RequestAuth) (*ResponseAuth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionSignup not implemented")
}
func (*UnimplementedAuthServer) ActionSignin(context.Context, *RequestAuth) (*ResponseAuth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionSignin not implemented")
}
func (*UnimplementedAuthServer) ActionReset(context.Context, *RequestAuth) (*ResponseAuth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionReset not implemented")
}
func (*UnimplementedAuthServer) SetLogout(context.Context, *RequestAuth) (*ResponseAuth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogout not implemented")
}
func (*UnimplementedAuthServer) GetRefresh(context.Context, *RequestAuth) (*ResponseAuth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRefresh not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_ActionSignup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ActionSignup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Auth/ActionSignup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ActionSignup(ctx, req.(*RequestAuth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ActionSignin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ActionSignin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Auth/ActionSignin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ActionSignin(ctx, req.(*RequestAuth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ActionReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ActionReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Auth/ActionReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ActionReset(ctx, req.(*RequestAuth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SetLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SetLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Auth/SetLogout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SetLogout(ctx, req.(*RequestAuth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Auth/GetRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetRefresh(ctx, req.(*RequestAuth))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActionSignup",
			Handler:    _Auth_ActionSignup_Handler,
		},
		{
			MethodName: "ActionSignin",
			Handler:    _Auth_ActionSignin_Handler,
		},
		{
			MethodName: "ActionReset",
			Handler:    _Auth_ActionReset_Handler,
		},
		{
			MethodName: "SetLogout",
			Handler:    _Auth_SetLogout_Handler,
		},
		{
			MethodName: "GetRefresh",
			Handler:    _Auth_GetRefresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/auth.proto",
}
