// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: server/proto/index.proto

package proto

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Statistic message structure.
type Statistic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accounts     *Statistic_Account     `protobuf:"bytes,1,opt,name=accounts,proto3" json:"accounts,omitempty"`
	Chains       *Statistic_Chain       `protobuf:"bytes,2,opt,name=chains,proto3" json:"chains,omitempty"`
	Currencies   *Statistic_Currency    `protobuf:"bytes,3,opt,name=currencies,proto3" json:"currencies,omitempty"`
	Pairs        *Statistic_Pair        `protobuf:"bytes,4,opt,name=pairs,proto3" json:"pairs,omitempty"`
	Transactions *Statistic_Transaction `protobuf:"bytes,5,opt,name=transactions,proto3" json:"transactions,omitempty"`
	Orders       *Statistic_Order       `protobuf:"bytes,6,opt,name=orders,proto3" json:"orders,omitempty"`
	Reserves     []*Statistic_Reserve   `protobuf:"bytes,7,rep,name=reserves,proto3" json:"reserves,omitempty"`
}

func (x *Statistic) Reset() {
	*x = Statistic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic) ProtoMessage() {}

func (x *Statistic) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic.ProtoReflect.Descriptor instead.
func (*Statistic) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{0}
}

func (x *Statistic) GetAccounts() *Statistic_Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *Statistic) GetChains() *Statistic_Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *Statistic) GetCurrencies() *Statistic_Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *Statistic) GetPairs() *Statistic_Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *Statistic) GetTransactions() *Statistic_Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Statistic) GetOrders() *Statistic_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Statistic) GetReserves() []*Statistic_Reserve {
	if x != nil {
		return x.Reserves
	}
	return nil
}

// Statistic structure.
type GetIndexRequestStatistic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetIndexRequestStatistic) Reset() {
	*x = GetIndexRequestStatistic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIndexRequestStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexRequestStatistic) ProtoMessage() {}

func (x *GetIndexRequestStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexRequestStatistic.ProtoReflect.Descriptor instead.
func (*GetIndexRequestStatistic) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{1}
}

type ResponseStatistic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields *Statistic `protobuf:"bytes,1,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ResponseStatistic) Reset() {
	*x = ResponseStatistic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStatistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatistic) ProtoMessage() {}

func (x *ResponseStatistic) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatistic.ProtoReflect.Descriptor instead.
func (*ResponseStatistic) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseStatistic) GetFields() *Statistic {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Currency structure.
type GetIndexRequestCurrencies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetIndexRequestCurrencies) Reset() {
	*x = GetIndexRequestCurrencies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIndexRequestCurrencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexRequestCurrencies) ProtoMessage() {}

func (x *GetIndexRequestCurrencies) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexRequestCurrencies.ProtoReflect.Descriptor instead.
func (*GetIndexRequestCurrencies) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{3}
}

func (x *GetIndexRequestCurrencies) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Pair structure.
type GetIndexRequestPairs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetIndexRequestPairs) Reset() {
	*x = GetIndexRequestPairs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIndexRequestPairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexRequestPairs) ProtoMessage() {}

func (x *GetIndexRequestPairs) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexRequestPairs.ProtoReflect.Descriptor instead.
func (*GetIndexRequestPairs) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{4}
}

type Statistic_Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable int32 `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Enable  int32 `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Statistic_Account) Reset() {
	*x = Statistic_Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Account) ProtoMessage() {}

func (x *Statistic_Account) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Account.ProtoReflect.Descriptor instead.
func (*Statistic_Account) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Statistic_Account) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

func (x *Statistic_Account) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type Statistic_Chain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable int32 `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Enable  int32 `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Statistic_Chain) Reset() {
	*x = Statistic_Chain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Chain) ProtoMessage() {}

func (x *Statistic_Chain) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Chain.ProtoReflect.Descriptor instead.
func (*Statistic_Chain) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Statistic_Chain) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

func (x *Statistic_Chain) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type Statistic_Currency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable int32 `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Enable  int32 `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Statistic_Currency) Reset() {
	*x = Statistic_Currency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Currency) ProtoMessage() {}

func (x *Statistic_Currency) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Currency.ProtoReflect.Descriptor instead.
func (*Statistic_Currency) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Statistic_Currency) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

func (x *Statistic_Currency) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type Statistic_Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disable int32 `protobuf:"varint,1,opt,name=disable,proto3" json:"disable,omitempty"`
	Enable  int32 `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Statistic_Pair) Reset() {
	*x = Statistic_Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Pair) ProtoMessage() {}

func (x *Statistic_Pair) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Pair.ProtoReflect.Descriptor instead.
func (*Statistic_Pair) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Statistic_Pair) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

func (x *Statistic_Pair) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type Statistic_Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filled  int32 `protobuf:"varint,1,opt,name=filled,proto3" json:"filled,omitempty"`
	Pending int32 `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
}

func (x *Statistic_Transaction) Reset() {
	*x = Statistic_Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Transaction) ProtoMessage() {}

func (x *Statistic_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Transaction.ProtoReflect.Descriptor instead.
func (*Statistic_Transaction) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Statistic_Transaction) GetFilled() int32 {
	if x != nil {
		return x.Filled
	}
	return 0
}

func (x *Statistic_Transaction) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type Statistic_Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buy  int32 `protobuf:"varint,1,opt,name=buy,proto3" json:"buy,omitempty"`
	Sell int32 `protobuf:"varint,2,opt,name=sell,proto3" json:"sell,omitempty"`
}

func (x *Statistic_Order) Reset() {
	*x = Statistic_Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Order) ProtoMessage() {}

func (x *Statistic_Order) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Order.ProtoReflect.Descriptor instead.
func (*Statistic_Order) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Statistic_Order) GetBuy() int32 {
	if x != nil {
		return x.Buy
	}
	return 0
}

func (x *Statistic_Order) GetSell() int32 {
	if x != nil {
		return x.Sell
	}
	return 0
}

type Statistic_Reserve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol              string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Value               float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueCharged        float64 `protobuf:"fixed64,3,opt,name=value_charged,json=valueCharged,proto3" json:"value_charged,omitempty"`
	ValueChargedConvert float64 `protobuf:"fixed64,4,opt,name=value_charged_convert,json=valueChargedConvert,proto3" json:"value_charged_convert,omitempty"`
	ValueCosts          float64 `protobuf:"fixed64,5,opt,name=value_costs,json=valueCosts,proto3" json:"value_costs,omitempty"`
}

func (x *Statistic_Reserve) Reset() {
	*x = Statistic_Reserve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_index_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Statistic_Reserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistic_Reserve) ProtoMessage() {}

func (x *Statistic_Reserve) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_index_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistic_Reserve.ProtoReflect.Descriptor instead.
func (*Statistic_Reserve) Descriptor() ([]byte, []int) {
	return file_server_proto_index_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Statistic_Reserve) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Statistic_Reserve) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Statistic_Reserve) GetValueCharged() float64 {
	if x != nil {
		return x.ValueCharged
	}
	return 0
}

func (x *Statistic_Reserve) GetValueChargedConvert() float64 {
	if x != nil {
		return x.ValueChargedConvert
	}
	return 0
}

func (x *Statistic_Reserve) GetValueCosts() float64 {
	if x != nil {
		return x.ValueCosts
	}
	return 0
}

var File_server_proto_index_proto protoreflect.FileDescriptor

var file_server_proto_index_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x07, 0x0a,
	0x09, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x34, 0x0a, 0x08, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x12, 0x2e, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x06, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52,
	0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x70,
	0x61, 0x69, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73,
	0x1a, 0x3b, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x39, 0x0a,
	0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x3c, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x38, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x1a, 0x3f, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x1a, 0x2d, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x75,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x62, 0x75, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x65, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x6c,
	0x1a, 0xb1, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x12,
	0x32, 0x0a, 0x15, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64,
	0x5f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x13,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63, 0x6f, 0x73,
	0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x43,
	0x6f, 0x73, 0x74, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x22, 0x3d, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x28, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x61, 0x69, 0x72, 0x73, 0x32, 0xc2, 0x02, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x6a,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x1a,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x19, 0x12, 0x17, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x67, 0x65, 0x74,
	0x2d, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x6f, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x1a, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22, 0x18,
	0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x67, 0x65, 0x74, 0x2d, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x5c, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x61, 0x69, 0x72, 0x73, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x18, 0x22, 0x13, 0x2f, 0x76, 0x32, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2f, 0x67, 0x65, 0x74,
	0x2d, 0x70, 0x61, 0x69, 0x72, 0x73, 0x3a, 0x01, 0x2a, 0x42, 0x0e, 0x5a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_server_proto_index_proto_rawDescOnce sync.Once
	file_server_proto_index_proto_rawDescData = file_server_proto_index_proto_rawDesc
)

func file_server_proto_index_proto_rawDescGZIP() []byte {
	file_server_proto_index_proto_rawDescOnce.Do(func() {
		file_server_proto_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_index_proto_rawDescData)
	})
	return file_server_proto_index_proto_rawDescData
}

var file_server_proto_index_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_server_proto_index_proto_goTypes = []interface{}{
	(*Statistic)(nil),                 // 0: proto.Statistic
	(*GetIndexRequestStatistic)(nil),  // 1: proto.GetIndexRequestStatistic
	(*ResponseStatistic)(nil),         // 2: proto.ResponseStatistic
	(*GetIndexRequestCurrencies)(nil), // 3: proto.GetIndexRequestCurrencies
	(*GetIndexRequestPairs)(nil),      // 4: proto.GetIndexRequestPairs
	(*Statistic_Account)(nil),         // 5: proto.Statistic.Account
	(*Statistic_Chain)(nil),           // 6: proto.Statistic.Chain
	(*Statistic_Currency)(nil),        // 7: proto.Statistic.Currency
	(*Statistic_Pair)(nil),            // 8: proto.Statistic.Pair
	(*Statistic_Transaction)(nil),     // 9: proto.Statistic.Transaction
	(*Statistic_Order)(nil),           // 10: proto.Statistic.Order
	(*Statistic_Reserve)(nil),         // 11: proto.Statistic.Reserve
	(*ResponseCurrency)(nil),          // 12: proto.ResponseCurrency
	(*ResponsePair)(nil),              // 13: proto.ResponsePair
}
var file_server_proto_index_proto_depIdxs = []int32{
	5,  // 0: proto.Statistic.accounts:type_name -> proto.Statistic.Account
	6,  // 1: proto.Statistic.chains:type_name -> proto.Statistic.Chain
	7,  // 2: proto.Statistic.currencies:type_name -> proto.Statistic.Currency
	8,  // 3: proto.Statistic.pairs:type_name -> proto.Statistic.Pair
	9,  // 4: proto.Statistic.transactions:type_name -> proto.Statistic.Transaction
	10, // 5: proto.Statistic.orders:type_name -> proto.Statistic.Order
	11, // 6: proto.Statistic.reserves:type_name -> proto.Statistic.Reserve
	0,  // 7: proto.ResponseStatistic.fields:type_name -> proto.Statistic
	1,  // 8: proto.Index.GetStatistic:input_type -> proto.GetIndexRequestStatistic
	3,  // 9: proto.Index.GetCurrencies:input_type -> proto.GetIndexRequestCurrencies
	4,  // 10: proto.Index.GetPairs:input_type -> proto.GetIndexRequestPairs
	2,  // 11: proto.Index.GetStatistic:output_type -> proto.ResponseStatistic
	12, // 12: proto.Index.GetCurrencies:output_type -> proto.ResponseCurrency
	13, // 13: proto.Index.GetPairs:output_type -> proto.ResponsePair
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_server_proto_index_proto_init() }
func file_server_proto_index_proto_init() {
	if File_server_proto_index_proto != nil {
		return
	}
	file_server_proto_exchange_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_server_proto_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIndexRequestStatistic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStatistic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIndexRequestCurrencies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIndexRequestPairs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Chain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Currency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_index_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Statistic_Reserve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_index_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_index_proto_goTypes,
		DependencyIndexes: file_server_proto_index_proto_depIdxs,
		MessageInfos:      file_server_proto_index_proto_msgTypes,
	}.Build()
	File_server_proto_index_proto = out.File
	file_server_proto_index_proto_rawDesc = nil
	file_server_proto_index_proto_goTypes = nil
	file_server_proto_index_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IndexClient is the client API for Index service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IndexClient interface {
	// Get statistic.
	GetStatistic(ctx context.Context, in *GetIndexRequestStatistic, opts ...grpc.CallOption) (*ResponseStatistic, error)
	// Index get currencies.
	GetCurrencies(ctx context.Context, in *GetIndexRequestCurrencies, opts ...grpc.CallOption) (*ResponseCurrency, error)
	// Index get pairs.
	GetPairs(ctx context.Context, in *GetIndexRequestPairs, opts ...grpc.CallOption) (*ResponsePair, error)
}

type indexClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexClient(cc grpc.ClientConnInterface) IndexClient {
	return &indexClient{cc}
}

func (c *indexClient) GetStatistic(ctx context.Context, in *GetIndexRequestStatistic, opts ...grpc.CallOption) (*ResponseStatistic, error) {
	out := new(ResponseStatistic)
	err := c.cc.Invoke(ctx, "/proto.Index/GetStatistic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetCurrencies(ctx context.Context, in *GetIndexRequestCurrencies, opts ...grpc.CallOption) (*ResponseCurrency, error) {
	out := new(ResponseCurrency)
	err := c.cc.Invoke(ctx, "/proto.Index/GetCurrencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) GetPairs(ctx context.Context, in *GetIndexRequestPairs, opts ...grpc.CallOption) (*ResponsePair, error) {
	out := new(ResponsePair)
	err := c.cc.Invoke(ctx, "/proto.Index/GetPairs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServer is the server API for Index service.
type IndexServer interface {
	// Get statistic.
	GetStatistic(context.Context, *GetIndexRequestStatistic) (*ResponseStatistic, error)
	// Index get currencies.
	GetCurrencies(context.Context, *GetIndexRequestCurrencies) (*ResponseCurrency, error)
	// Index get pairs.
	GetPairs(context.Context, *GetIndexRequestPairs) (*ResponsePair, error)
}

// UnimplementedIndexServer can be embedded to have forward compatible implementations.
type UnimplementedIndexServer struct {
}

func (*UnimplementedIndexServer) GetStatistic(context.Context, *GetIndexRequestStatistic) (*ResponseStatistic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistic not implemented")
}
func (*UnimplementedIndexServer) GetCurrencies(context.Context, *GetIndexRequestCurrencies) (*ResponseCurrency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrencies not implemented")
}
func (*UnimplementedIndexServer) GetPairs(context.Context, *GetIndexRequestPairs) (*ResponsePair, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPairs not implemented")
}

func RegisterIndexServer(s *grpc.Server, srv IndexServer) {
	s.RegisterService(&_Index_serviceDesc, srv)
}

func _Index_GetStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexRequestStatistic)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetStatistic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetStatistic(ctx, req.(*GetIndexRequestStatistic))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexRequestCurrencies)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetCurrencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetCurrencies(ctx, req.(*GetIndexRequestCurrencies))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_GetPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexRequestPairs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).GetPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Index/GetPairs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).GetPairs(ctx, req.(*GetIndexRequestPairs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Index_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Index",
	HandlerType: (*IndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatistic",
			Handler:    _Index_GetStatistic_Handler,
		},
		{
			MethodName: "GetCurrencies",
			Handler:    _Index_GetCurrencies_Handler,
		},
		{
			MethodName: "GetPairs",
			Handler:    _Index_GetPairs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/index.proto",
}
