name: 'Push To ECR'

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt install -y python3.10-venv
      - uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - uses: actions/checkout@v2

      - run: docker build --tag envoys-backend-pg -f Dockerfile.PostgreSQL .
      - name: Push pg
        id: ecr_pg
        uses: jwalton/gh-ecr-push@v1.3.6
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: envoys-backend-pg
          image: envoys-backend-pg:${{ github.sha }}, envoys-backend-pg:latest

      - run: docker build --tag envoys-backend-rabbit -f Dockerfile.RabbitMQ .
      - name: Push rabbit
        id: ecr_rabbit
        uses: jwalton/gh-ecr-push@v1.3.6
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: envoys-backend-rabbit
          image: envoys-backend-rabbit:${{ github.sha }}, envoys-backend-rabbit:latest
      
      - run: docker build --tag envoys-backend-redis -f Dockerfile.Redis .
      - name: Push redis
        id: ecr_redis
        uses: jwalton/gh-ecr-push@v1.3.6
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: envoys-backend-redis
          image: envoys-backend-redis:${{ github.sha }}, envoys-backend-redis:latest
      
      - run: docker build --tag envoys-backend -f Dockerfile .
      - name: Push backend
        id: ecr_backend
        uses: jwalton/gh-ecr-push@v1.3.6
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: envoys-backend
          image: envoys-backend:${{ github.sha }}, envoys-backend:latest
      