name: 'Push To Dockerhub'

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push pg
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.PostgreSQL
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-envoys-pg:latest,${{ secrets.DOCKERHUB_USERNAME }}/backend-envoys-pg:${{ github.sha }}
      -
        name: Build and push rabbit
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.RabbitMQ
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-envoys-rabbit:latest,${{ secrets.DOCKERHUB_USERNAME }}/backend-envoys-rabbit:${{ github.sha }}
      -
        name: Build and push redis
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.Redis
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-envoys-redis:latest,${{ secrets.DOCKERHUB_USERNAME }}/backend-envoys-redis:${{ github.sha }}
      -
        name: Build and push server
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-envoys:latest,${{ secrets.DOCKERHUB_USERNAME }}/backend-envoys:${{ github.sha }}